// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neo4j.app.trivialt.model;

import java.lang.String;

privileged aspect Answer_Roo_JavaBean {
    
    public String Answer.getText() {
        return this.text;
    }
    
    public void Answer.setText(String text) {
        this.text = text;
    }
    
}
