// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neo4j.app.trivialt.service;

import java.lang.Long;

privileged aspect Indicator_Roo_JavaBean {
    
    public Long Indicator.getId() {
        return this.id;
    }
    
    public void Indicator.setId(Long id) {
        this.id = id;
    }
    
}
