// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neo4j.app.trivialt.service;

import java.lang.Boolean;

privileged aspect Toggle_Roo_JavaBean {
    
    public Boolean Toggle.getState() {
        return this.state;
    }
    
    public void Toggle.setState(Boolean state) {
        this.state = state;
    }
    
}
