#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

if [ "$1" == "" ]; then
  echo "Usage: feature-match <match-id>"
  exit 1
fi

MATCH_ID=$1

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"
REST_ENDPOINT="${TRIVIALT_URL}api/trivialt/feature"

CURL_OPTS="--silent --fail -H Accept:application/json -H Content-Type:application/json"
PAYLOAD="{ \"id\" : ${MATCH_ID} }"

curl -d "${PAYLOAD}" ${CURL_OPTS} ${REST_ENDPOINT}

