#!/bin/sh

if [ "$1" == "" ]; then
  echo "Usage: get-current-round <match-id>"
  exit
fi

MATCH_ID=$1

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"
REST_ENDPOINT="${TRIVIALT_URL}api/matches/${MATCH_ID}"

CURL_OPTS="--silent --fail -H Accept:application/json -H Content-Type:application/json"


JSON=$(curl ${CURL_OPTS} ${REST_ENDPOINT} || echo "{ }")

echo $JSON | jgrep -s currentRound.id
