#!/bin/sh

if [ "$1" == "" ]; then
echo "Usage: get-match-rounds <match-id>"
exit
fi

MATCH_ID=$1

curl --verbose -H Accept:application/json -H Content-Type:application/json http://localhost:8080/trivialt-roo/api/matches/${MATCH_ID}/rounds
