#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"

REST_ENDPOINT="${TRIVIALT_URL}api/matches/featured"
CURL_OPTS="--fail --silent -H Accept:application/json -H Content-Type:application/json"

( curl ${CURL_OPTS} ${REST_ENDPOINT} || echo "{ }" ) | jgrep

