#!/bin/sh

if [ "$1" == "" ]; then
echo "Usage: get-current-deck <team-id>"
exit
fi

TEAM_ID=$1

SCRIPT=`basename $0`

JSON=`curl --silent -H Accept:application/json -H Content-Type:application/json http://localhost:8080/trivialt-roo/api/teams/${TEAM_ID}/decks/current`

echo $JSON | jgrep -s id
