#!/bin/sh

if [ "$1" == "" ]; then
echo "Usage: get-deck-cards <deck-id>"
exit
fi

DECK_ID=$1
JSON_RESULT="./deck_${DECK_ID}.json"

curl --silent -H Accept:application/json -H Content-Type:application/json http://localhost:8080/trivialt-roo/api/decks/${DECK_ID}/cards > ${JSON_RESULT}
