#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"


if [ "$1" == "" ]; then
echo "Usage: get-current-deck <team-id>"
exit
fi

TEAM_ID=$1

SCRIPT=`basename $0`

JSON=$( ( curl --fail --silent -H Accept:application/json -H Content-Type:application/json ${TRIVIALT_URL}api/teams/${TEAM_ID}/decks/current || echo "{ }" ) | jgrep -s id )

if [ -z "${JSON}" ]; then
  echo "${JSON}"
else
  exit 1
fi
