#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"

( curl --fail --silent -H Accept:application/json -H Content-Type:application/json ${TRIVIALT_URL}api/cards || echo "{ }" ) | jgrep -s "id deck.team.name round.title"
