#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"

REST_ENDPOINT="${TRIVIALT_URL}api/answers"
CURL_OPTS="--silent -H Accept:application/json -H Content-Type:application/json"

if [ "$1" == "" ]; then
  echo "Usage: mkanswer <answer-text>"
  exit 1
fi

ANSWER=$1

SCRIPT=`basename $0`
JSON_RESULT="./${ANSWER}.json"

curl -d "{ \"text\" : \"${ANSWER}\"}" ${CURL_OPTS} ${REST_ENDPOINT} > ${JSON_RESULT}


