#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

if [ "$1" == "" ]; then
  echo "Usage: mkframe4question <question-id> [<round-id>]"
  exit 1
fi

QUESTON=$1

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"

CURL_OPTS="--silent --fail -H Accept:application/json -H Content-Type:application/json"
PAYLOAD="{}"

if [ "$2" == "" ]; then
  # make a frame not in around
else
  # make a frame attached to a round
  REST_ENDPOINT="${TRIVIALT_URL}api/rounds/${2}/questions"
  PAYLOAD="{ \"questionId\":\"${QUESTION}\" }"
fi

curl -d "${PAYLOAD}" ${CURL_OPTS} ${REST_ENDPOINT}

