#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"
REST_ENDPOINT="${TRIVIALT_URL}api/matches"
CURL_OPTS="--verbose --fail -H Accept:application/json -H Content-Type:application/json"

if [ "$1" == "" ]; then
  echo "Usage: mkmatch <match.json>"
  exit 1
fi

curl -d @"${1}" ${CURL_OPTS} ${REST_ENDPOINT}

