#!/bin/sh

function usage {
  echo "Usage: mkproposal <card-id> <framedQuestion-id> <answer-text>"
}

if [ $# -ne "3" ]; then
  usage
  exit 1
fi

CARD_ID=$1
QUESTION_ID=$2
ANSWER=$3

SCRIPT=`basename $0`
JSON_RESULT="./${TEAM}.json"

curl -d "{name:\"${TEAM}\"}" --silent -H Accept:application/json -H Content-Type:application/json http://localhost:8080/trivialt-roo/api/teams > ${JSON_RESULT}


