#!/bin/sh

if [ "$1" == "" || "$2" == "" ]; then
  echo "Usage: mkround-in-match <match-id> <round.json>"
  exit 1
fi

MATCH_ID=${1}

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"
REST_ENDPOINT="${TRIVIALT_URL}api/matches/${1}/rounds"
CURL_OPTS="--verbose --fail -H Accept:application/json -H Content-Type:application/json"

curl -d @"${2}" ${CURL_OPTS} ${REST_ENDPOINT}

if [ $? ]; then echo "Failed"; exit 1; fi

