#!/bin/sh

if [ -e "./trivialt.conf" ]; then source "./trivialt.conf"; fi

TRIVIALT_HOST=${TRIVIALT_HOST:="localhost:8080"}
TRIVIALT_BASE=${TRIVIALT_BASE:="/trivialt-roo/"}
TRIVIALT_URL="http://${TRIVIALT_HOST}${TRIVIALT_BASE}"

STATUS=$(curl --fail -s -o /dev/null -w "%{http_code}" "${TRIVIALT_URL}")

if [ ${STATUS} != "200" ]; then echo ${TRIVIALT_URL} not available; exit 1; fi

exit 0

